In [1]:
import numpy as np
import LanczosCGApproximateGPs as gp

In [8]:
sample_size = 100
max_iter = 10
noise_level = 1

X = np.array([np.linspace(0, 1, sample_size)])
X = X.transpose()
eps = np.random.normal(0, noise_level, sample_size)
f = X[:, 0]
Y = f + eps
print(Y)

actions = []
index = 0
for iter in range(0, max_iter):
    action = np.zeros(sample_size)
    action[index] = 1
    actions.append(action)
    index = index + 1

[ 1.46119931  0.46749914 -0.27343995 -1.03447774  0.52810173  2.2118859
  0.04586172  1.40545016 -0.88371936 -1.46467781 -0.37248388 -0.50433348
  1.6338727   0.97939182 -1.60014541  0.64304091  0.0867822  -0.85649737
 -0.01968357 -0.46915782  1.75298398  0.07939788 -0.25264659  1.15814888
 -0.0217464  -0.63666784 -1.39247456  0.67750764  0.84566404  1.1326687
  1.20711762 -2.08556133 -0.43058101 -0.12743447 -0.4281019  -0.27065679
  0.35453108  1.20141517  0.49030103  0.31444503 -1.79877987  1.02517186
  2.54033632 -0.81914796  0.43882377 -0.89318414  0.75587983 -1.18861999
  1.76346706  1.93517451  1.2865612   1.8711832   1.2186853   0.27026212
 -2.15799718 -2.2104038   1.02692689 -0.95639308  1.06294648 -1.00284743
 -0.69873776  2.11816194  0.61910311  0.5944275   1.7898815   0.90580939
 -0.63454772  1.21641006 -0.26223373  0.27180261  0.19834869  2.34192112
  0.74971665 -1.47803768 -0.0084965  -0.32541995  0.88127711 -0.59225704
  1.07021795 -0.27552646  0.24825832  0.81464302  0.4

In [3]:
def gaussian_kernel(x, y):
    z = np.minimum(x, y)
    return z

In [4]:
print(X)
gaussian_kernel(X, X)

[[0.  ]
 [0.25]
 [0.5 ]
 [0.75]
 [1.  ]]


array([[0.  ],
       [0.25],
       [0.5 ],
       [0.75],
       [1.  ]])

In [5]:
algorithm = gp.Iter_GP(X, Y, noise_level, actions, kernel = gaussian_kernel)
algorithm.iter_forward(sample_size)

In [6]:
algorithm.kernel_matrix
print(algorithm.approx_augmented_inverse)

K_sigma = algorithm.augmented_kernel_matrix
inverse = np.linalg.inv(K_sigma)
inverse

[[ 1.          0.          0.          0.          0.        ]
 [ 0.          0.84463519 -0.09957082 -0.06866953 -0.05493562]
 [ 0.         -0.09957082  0.77596567 -0.15450644 -0.12360515]
 [ 0.         -0.06866953 -0.15450644  0.72103004 -0.22317597]
 [ 0.         -0.05493562 -0.12360515 -0.22317597  0.62145923]]


array([[ 1.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.84463519, -0.09957082, -0.06866953, -0.05493562],
       [ 0.        , -0.09957082,  0.77596567, -0.15450644, -0.12360515],
       [ 0.        , -0.06866953, -0.15450644,  0.72103004, -0.22317597],
       [ 0.        , -0.05493562, -0.12360515, -0.22317597,  0.62145923]])

In [7]:
print(algorithm.approx_posterior_mean(X))
print(f)

[0.         0.74535969 1.48789059 1.9368423  2.23220332]
[0.   0.25 0.5  0.75 1.  ]
