In [1]:
import numpy as np
import LanczosCGApproximateGPs as gp

In [2]:
sample_size = 5
max_iter = 5
noise_level = 1

X = np.array([np.linspace(0, 1, sample_size)])
X = X.transpose()
Y = X[:, 0]**2
print(Y)

actions = []
index = 0
for iter in range(0, max_iter):
    action = np.zeros(sample_size)
    action[index] = 1
    actions.append(action)
    index = index + 1

[0.     0.0625 0.25   0.5625 1.    ]


In [3]:
def gaussian_kernel(x, y):
    z = np.minimum(x, y)
    return z

In [4]:
algorithm = gp.Iter_GP(X, Y, noise_level, actions, kernel = gaussian_kernel)

x = np.array([0, 1, 2])
y = np.array([1, 0, 2])
algorithm.kernel(x, 0)

algorithm.kernel_matrix

array([[0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.25, 0.25, 0.25, 0.25],
       [0.  , 0.25, 0.5 , 0.5 , 0.5 ],
       [0.  , 0.25, 0.5 , 0.75, 0.75],
       [0.  , 0.25, 0.5 , 0.75, 1.  ]])

In [5]:
algorithm.kernel_matrix
algorithm.augmented_kernel_matrix

K_sigma = algorithm.augmented_kernel_matrix
inverse = np.linalg.inv(K_sigma)
inverse

array([[ 1.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.84463519, -0.09957082, -0.06866953, -0.05493562],
       [ 0.        , -0.09957082,  0.77596567, -0.15450644, -0.12360515],
       [ 0.        , -0.06866953, -0.15450644,  0.72103004, -0.22317597],
       [ 0.        , -0.05493562, -0.12360515, -0.22317597,  0.62145923]])

In [6]:
algorithm.iter_forward(3)

In [7]:
algorithm.iter

3

In [8]:
algorithm.low_rank_augmented_inverse

array([[ 1.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.82758621, -0.13793103,  0.        ,  0.        ],
       [ 0.        , -0.13793103,  0.68965517,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ]])

In [10]:
algorithm.iter_forward?

Signature: algorithm.iter_forward(iter_num)
Docstring: Performs iter_num iterations of the Iter_GP algorithm.
File:      ~/Projects/LanczosCGApproximateGPs/src/LanczosCGApproximateGPs/Iter_GP.py
Type:      method